j = {'took': 25, 'timed_out': False, '_shards': {'total': 1, 'successful': 1, 'skipped': 0, 'failed': 0},
     'hits': {'total': {'value': 10000, 'relation': 'gte'}, 'max_score': 1.0, 'hits': [
         {'_index': 'person_apollo', '_type': '_doc', '_id': '4a7c414304fb3b52275547fa6833533d', '_score': 1.0,
          '_source': {'username': 'Brian Schell', 'first_name': 'brian', 'last_name': 'schell', 'name': 'brian schell',
                      'person_title': 'Technical Support Representative', 'person_functions': "['support']",
                      'person_seniority': 'entry', 'person_email_status_cd': 'Extrapolated',
                      'person_extrapolated_email_confidence': '0.73', 'person_email': 'bschell@cablevision.com',
                      'person_phone': '', 'person_sanitized_phone': '',
                      'person_email_analyzed': 'bschell@cablevision.com',
                      'person_linkedin_url': 'http://www.linkedin.com/in/brianwschell',
                      'person_detailed_function': 'technical support representative',
                      'person_title_normalized': 'technical support representative',
                      'primary_title_normalized_for_faceting': 'Technical Support Representative',
                      'sanitized_organization_name_unanalyzed': 'cablevision', 'person_location_city': 'New York',
                      'person_location_city_with_state_or_country': 'New York, New York',
                      'person_location_state': 'New York', 'person_location_state_with_country': 'New York, US',
                      'person_location_country': 'United States', 'person_location_postal_code': '',
                      'job_start_date': '2005-05-01', 'current_organization_ids': "['55f8073ef3e5bb76430020d1']",
                      'modality': 'people', 'prospected_by_team_ids': '', 'person_excluded_by_team_ids': '',
                      'relavence_boost': '0.4204692619390966', 'person_num_linkedin_connections': '66',
                      'person_location_geojson': "{'type': 'envelope', 'coordinates': [[-74.255735, 40.9152555], [-73.70027209999999, 40.496044]]}",
                      'predictive_scores': "{'551e3ef07261695147160000': 0.9440106634708865}",
                      'person_vacuumed_at': '2018-04-17T19:19:48.000+00:00'}},
         {'_index': 'person_apollo', '_type': '_doc', '_id': 'bd23b2226c421e8c149c3d1f21b831a6', '_score': 1.0,
          '_source': {'username': 'Joe Kraisorn', 'first_name': 'joe', 'last_name': 'kraisorn', 'name': 'joe kraisorn',
                      'person_title': 'Senior Product Manager', 'person_functions': "['product_management']",
                      'person_seniority': 'manager', 'person_email_status_cd': 'Unavailable',
                      'person_extrapolated_email_confidence': '', 'person_email': '', 'person_phone': '',
                      'person_sanitized_phone': '', 'person_email_analyzed': '',
                      'person_linkedin_url': 'http://www.linkedin.com/in/joe-kraisorn-35a842',
                      'person_detailed_function': 'product', 'person_title_normalized': 'senior product manager',
                      'primary_title_normalized_for_faceting': 'Senior Product Manager',
                      'sanitized_organization_name_unanalyzed': 'samsung electronics america',
                      'person_location_city': 'New York',
                      'person_location_city_with_state_or_country': 'New York, New York',
                      'person_location_state': 'New York', 'person_location_state_with_country': 'New York, US',
                      'person_location_country': 'United States', 'person_location_postal_code': '',
                      'job_start_date': '2015-06-01',
                      'current_organization_ids': "['55921dd173696419080b7900', '54a1214369702d8ccc18ad02']",
                      'modality': 'people',
                      'prospected_by_team_ids': "['58e4152a9d796864c401b103', '5967acd29d79688807ebfcc9']",
                      'person_excluded_by_team_ids': '', 'relavence_boost': '0.4216606101084865',
                      'person_num_linkedin_connections': '500',
                      'person_location_geojson': "{'type': 'envelope', 'coordinates': [[-74.255735, 40.9152555], [-73.70027209999999, 40.496044]]}",
                      'predictive_scores': "{'551e3ef07261695147160000': 0.96252499250989}",
                      'person_vacuumed_at': '2018-04-11T12:19:59.000+00:00'}},
         {'_index': 'person_apollo', '_type': '_doc', '_id': 'a9988c780f76c4a3e235508e0a56e4ca', '_score': 1.0,
          '_source': {'username': 'Nguyen Quyet', 'first_name': 'nguyen', 'last_name': 'quyet', 'name': 'nguyen quyet',
                      'person_title': 'General Manager, Marketing Research, VN', 'person_functions': "['marketing']",
                      'person_seniority': 'manager', 'person_email_status_cd': 'Unavailable',
                      'person_extrapolated_email_confidence': '', 'person_email': '', 'person_phone': '',
                      'person_sanitized_phone': '', 'person_email_analyzed': '',
                      'person_linkedin_url': 'http://www.linkedin.com/in/nguyen-song-quyet-b542792b',
                      'person_detailed_function': 'general manager marketing research vn',
                      'person_title_normalized': 'general manager marketing research vn',
                      'primary_title_normalized_for_faceting': 'General Manager Marketing Research Vn',
                      'sanitized_organization_name_unanalyzed': 'vietnam airlines', 'person_location_city': '',
                      'person_location_city_with_state_or_country': '', 'person_location_state': '',
                      'person_location_state_with_country': '', 'person_location_country': 'Vietnam',
                      'person_location_postal_code': '', 'job_start_date': '',
                      'current_organization_ids': "['55923a90736964198132e100']", 'modality': 'people',
                      'prospected_by_team_ids': '', 'person_excluded_by_team_ids': '',
                      'relavence_boost': '-0.13068528194400547', 'person_num_linkedin_connections': '1',
                      'person_location_geojson': '', 'predictive_scores': '',
                      'person_vacuumed_at': '2017-12-30T20:01:13.000+00:00'}},
         {'_index': 'person_apollo', '_type': '_doc', '_id': 'b232fda78d0b74429c10ec02c892fa70', '_score': 1.0,
          '_source': {'username': 'Chris Bachman', 'first_name': 'chris', 'last_name': 'bachman',
                      'name': 'chris bachman', 'person_title': 'Consultant', 'person_functions': "['consulting']",
                      'person_seniority': 'entry', 'person_email_status_cd': 'Unavailable',
                      'person_extrapolated_email_confidence': '', 'person_email': '', 'person_phone': '',
                      'person_sanitized_phone': '', 'person_email_analyzed': '',
                      'person_linkedin_url': 'http://www.linkedin.com/in/chris-bachman-7b057b14',
                      'person_detailed_function': 'consultant', 'person_title_normalized': 'consultant',
                      'primary_title_normalized_for_faceting': 'Consultant',
                      'sanitized_organization_name_unanalyzed': 'tetra tech em inc',
                      'person_location_city': 'Washington',
                      'person_location_city_with_state_or_country': 'Washington, District of Columbia',
                      'person_location_state': 'District of Columbia',
                      'person_location_state_with_country': 'District of Columbia, US',
                      'person_location_country': 'United States', 'person_location_postal_code': '',
                      'job_start_date': '', 'current_organization_ids': "['55922734736964188a289c00']",
                      'modality': 'people', 'prospected_by_team_ids': '', 'person_excluded_by_team_ids': '',
                      'relavence_boost': '0.08332133440562162', 'person_num_linkedin_connections': '16',
                      'person_location_geojson': "{'type': 'envelope', 'coordinates': [[-77.1197401, 38.995548], [-76.909393, 38.8031494]]}",
                      'predictive_scores': "{'551e3ef07261695147160000': 0.14563219585567627}",
                      'person_vacuumed_at': '2018-01-26T12:49:58.000+00:00'}},
         {'_index': 'person_apollo', '_type': '_doc', '_id': 'f1cd8804c0cdc7bcf06e61a0ec0175eb', '_score': 1.0,
          '_source': {'username': 'Yasuhisa Kaneda', 'first_name': 'yasuhisa', 'last_name': 'kaneda',
                      'name': 'yasuhisa kaneda', 'person_title': 'Senior stuff / Product & Color Material Finish Team',
                      'person_functions': '', 'person_seniority': 'senior', 'person_email_status_cd': 'Unavailable',
                      'person_extrapolated_email_confidence': '', 'person_email': '', 'person_phone': '',
                      'person_sanitized_phone': '', 'person_email_analyzed': '',
                      'person_linkedin_url': 'http://www.linkedin.com/in/yasuhisa-kaneda-805b11b',
                      'person_detailed_function': 'stuff product color material finish',
                      'person_title_normalized': 'senior stuff product color material finish team',
                      'primary_title_normalized_for_faceting': 'Senior Stuff Product And Color Material Finish Team',
                      'sanitized_organization_name_unanalyzed': 'seiko epson corporation japan',
                      'person_location_city': 'Tokyo', 'person_location_city_with_state_or_country': 'Tokyo, Japan',
                      'person_location_state': '', 'person_location_state_with_country': '',
                      'person_location_country': 'Japan', 'person_location_postal_code': '',
                      'job_start_date': '2016-01-01', 'current_organization_ids': "['54a1359a69702d2f9fc11c01']",
                      'modality': 'people', 'prospected_by_team_ids': '', 'person_excluded_by_team_ids': '',
                      'relavence_boost': '0.21743872698956368', 'person_num_linkedin_connections': '64',
                      'person_location_geojson': "{'type': 'envelope', 'coordinates': [[139.5629047, 35.8175168], [139.9198562, 35.5208632]]}",
                      'predictive_scores': "{'551e3ef07261695147160000': 0.37806406642657553}",
                      'person_vacuumed_at': '2018-04-24T16:38:11.000+00:00'}},
         {'_index': 'person_apollo', '_type': '_doc', '_id': 'a8c68154da6cd3d47c6c128e18de2e4d', '_score': 1.0,
          '_source': {'username': 'Franck Charles', 'first_name': 'franck', 'last_name': 'charles',
                      'name': 'franck charles', 'person_title': 'Chauffeur de maître', 'person_functions': '',
                      'person_seniority': 'entry', 'person_email_status_cd': 'Unavailable',
                      'person_extrapolated_email_confidence': '', 'person_email': '', 'person_phone': '',
                      'person_sanitized_phone': '', 'person_email_analyzed': '',
                      'person_linkedin_url': 'http://www.linkedin.com/in/franck-charles-788426104',
                      'person_detailed_function': 'chauffeur de maître',
                      'person_title_normalized': 'chauffeur de maître',
                      'primary_title_normalized_for_faceting': 'Chauffeur De Maître',
                      'sanitized_organization_name_unanalyzed': 'private driver', 'person_location_city': 'Paris',
                      'person_location_city_with_state_or_country': 'Paris, France',
                      'person_location_state': 'Île-de-France',
                      'person_location_state_with_country': 'Île-de-France, France',
                      'person_location_country': 'France', 'person_location_postal_code': '', 'job_start_date': '',
                      'current_organization_ids': "['5a9eb685a6da98d94d915c2f']", 'modality': 'people',
                      'prospected_by_team_ids': '', 'person_excluded_by_team_ids': '',
                      'relavence_boost': '-0.039056208756589966', 'person_num_linkedin_connections': '4',
                      'person_location_geojson': "{'type': 'envelope', 'coordinates': [[2.2241989, 48.8803319], [2.301587, 48.8338419]]}",
                      'predictive_scores': '', 'person_vacuumed_at': '2018-02-10T12:01:21.000+00:00'}},
         {'_index': 'person_apollo', '_type': '_doc', '_id': 'f2ec6b9b8767bf20d46b1ccd827e6927', '_score': 1.0,
          '_source': {'username': 'Gwenda Alexander', 'first_name': 'gwenda', 'last_name': 'alexander',
                      'name': 'gwenda alexander', 'person_title': 'Procurement Coordinator', 'person_functions': '',
                      'person_seniority': 'entry', 'person_email_status_cd': 'Extrapolated',
                      'person_extrapolated_email_confidence': '0.9',
                      'person_email': 'gwenda.alexander@aftonchemical.com', 'person_phone': '',
                      'person_sanitized_phone': '', 'person_email_analyzed': 'gwenda.alexander@aftonchemical.com',
                      'person_linkedin_url': 'http://www.linkedin.com/in/gwenda-alexander-91602159',
                      'person_detailed_function': 'procurement', 'person_title_normalized': 'procurement coordinator',
                      'primary_title_normalized_for_faceting': 'Procurement Coordinator',
                      'sanitized_organization_name_unanalyzed': 'afton chemical', 'person_location_city': 'Pasadena',
                      'person_location_city_with_state_or_country': 'Pasadena, Texas', 'person_location_state': 'Texas',
                      'person_location_state_with_country': 'Texas, US', 'person_location_country': 'United States',
                      'person_location_postal_code': '', 'job_start_date': '1997-04-01',
                      'current_organization_ids': "['54a198e37468694012b27600']", 'modality': 'people',
                      'prospected_by_team_ids': "['598e0e189d79680e40c3d7fe']", 'person_excluded_by_team_ids': '',
                      'relavence_boost': '0.3258096538021482', 'person_num_linkedin_connections': '25',
                      'person_location_geojson': "{'type': 'envelope', 'coordinates': [[-95.2345419, 29.739927], [-94.982734, 29.5578635]]}",
                      'predictive_scores': '', 'person_vacuumed_at': '2018-01-29T22:52:49.000+00:00'}},
         {'_index': 'person_apollo', '_type': '_doc', '_id': '4e3d62f48c573d40a4fc55308b909bda', '_score': 1.0,
          '_source': {'username': 'Hans Makkreel', 'first_name': 'hans', 'last_name': 'makkreel',
                      'name': 'hans makkreel', 'person_title': 'Oracle DBA', 'person_functions': '',
                      'person_seniority': 'entry', 'person_email_status_cd': 'Extrapolated',
                      'person_extrapolated_email_confidence': '0.74', 'person_email': 'hans.makkreel@capgemini.com',
                      'person_phone': '', 'person_sanitized_phone': '',
                      'person_email_analyzed': 'hans.makkreel@capgemini.com',
                      'person_linkedin_url': 'http://www.linkedin.com/in/hans-heijne-makkreel-a96b077',
                      'person_detailed_function': 'oracle dba', 'person_title_normalized': 'oracle dba',
                      'primary_title_normalized_for_faceting': 'Oracle Dba',
                      'sanitized_organization_name_unanalyzed': 'capgemini', 'person_location_city': 'Almere',
                      'person_location_city_with_state_or_country': 'Almere, Netherlands',
                      'person_location_state': 'Flevoland',
                      'person_location_state_with_country': 'Flevoland, Netherlands',
                      'person_location_country': 'Netherlands', 'person_location_postal_code': '',
                      'job_start_date': '1998-01-01', 'current_organization_ids': "['54a1204669702da753772d02']",
                      'modality': 'people', 'prospected_by_team_ids': '', 'person_excluded_by_team_ids': '',
                      'relavence_boost': '0.49836066217083363', 'person_num_linkedin_connections': '145',
                      'person_location_geojson': "{'type': 'envelope', 'coordinates': [[5.125622, 52.4354404], [5.3790797, 52.30354930000001]]}",
                      'predictive_scores': "{'551e3ef07261695147160000': 0.9615344636775522}",
                      'person_vacuumed_at': '2018-04-28T23:49:14.000+00:00'}},
         {'_index': 'person_apollo', '_type': '_doc', '_id': '1ee0ed0fa803708a76f10cb47cfa2a94', '_score': 1.0,
          '_source': {'username': 'Brian Chez', 'first_name': 'brian', 'last_name': 'chez', 'name': 'brian chez',
                      'person_title': 'Director', 'person_functions': '', 'person_seniority': 'director',
                      'person_email_status_cd': 'Extrapolated', 'person_extrapolated_email_confidence': '0.97',
                      'person_email': 'brian.chez@credit-suisse.com', 'person_phone': '', 'person_sanitized_phone': '',
                      'person_email_analyzed': 'brian.chez@credit-suisse.com',
                      'person_linkedin_url': 'http://www.linkedin.com/in/brian-chez-057b46',
                      'person_detailed_function': 'director', 'person_title_normalized': 'director',
                      'primary_title_normalized_for_faceting': 'Director',
                      'sanitized_organization_name_unanalyzed': 'credit suisse', 'person_location_city': 'New York',
                      'person_location_city_with_state_or_country': 'New York, New York',
                      'person_location_state': 'New York', 'person_location_state_with_country': 'New York, US',
                      'person_location_country': 'United States', 'person_location_postal_code': '',
                      'job_start_date': '2007-04-01', 'current_organization_ids': "['54a11e2569702d7fe69e6801']",
                      'modality': 'people', 'prospected_by_team_ids': '', 'person_excluded_by_team_ids': '',
                      'relavence_boost': '0.8216606101084865', 'person_num_linkedin_connections': '500',
                      'person_location_geojson': "{'type': 'envelope', 'coordinates': [[-74.255735, 40.9152555], [-73.70027209999999, 40.496044]]}",
                      'predictive_scores': '', 'person_vacuumed_at': '2018-04-09T16:57:13.000+00:00'}},
         {'_index': 'person_apollo', '_type': '_doc', '_id': 'aa620974f7c3d3d18df5372659fc8841', '_score': 1.0,
          '_source': {'username': 'Linz Wilbur', 'first_name': 'linz', 'last_name': 'wilbur', 'name': 'linz wilbur',
                      'person_title': 'Associate', 'person_functions': '', 'person_seniority': 'entry',
                      'person_email_status_cd': 'Extrapolated', 'person_extrapolated_email_confidence': '0.6',
                      'person_email': 'linz@planetarycollective.com', 'person_phone': '', 'person_sanitized_phone': '',
                      'person_email_analyzed': 'linz@planetarycollective.com',
                      'person_linkedin_url': 'http://www.linkedin.com/in/lindseak',
                      'person_detailed_function': 'associate', 'person_title_normalized': 'associate',
                      'primary_title_normalized_for_faceting': 'Associate',
                      'sanitized_organization_name_unanalyzed': 'planetary collective', 'person_location_city': '',
                      'person_location_city_with_state_or_country': '', 'person_location_state': '',
                      'person_location_state_with_country': '', 'person_location_country': 'United States',
                      'person_location_postal_code': '', 'job_start_date': '2013-07-01',
                      'current_organization_ids': "['54a1275969702d9313d59100', '5a9e431fa6da98d977f9e85f', '5a9e5461a6da98d98c6d2664']",
                      'modality': 'people', 'prospected_by_team_ids': '', 'person_excluded_by_team_ids': '',
                      'relavence_boost': '0.8216606101084865', 'person_num_linkedin_connections': '500',
                      'person_location_geojson': '', 'predictive_scores': '',
                      'person_vacuumed_at': '2018-03-03T12:41:19.000+00:00'}}]}}
